# Generated by Django 5.0.1 on 2024-01-20 18:07

import django.db.models.deletion
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=16)),
                ('title', models.TextField(default='')),
                ('arrows_and_circles', models.JSONField(default=web.models.Board.daac)),
                ('current_index', models.JSONField(default=[0])),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_uid', models.CharField(max_length=16)),
                ('title', models.TextField(default='')),
                ('current_board', models.IntegerField(default=0)),
                ('boards', models.ManyToManyField(to='web.board')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField()),
                ('txt', models.TextField()),
                ('orientation', models.TextField()),
                ('comment', models.TextField()),
                ('main_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.variant')),
                ('parent_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_variants', to='web.variant')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='variants',
            field=models.ManyToManyField(blank=True, to='web.variant'),
        ),
        migrations.CreateModel(
            name='VRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_set', to='web.variant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_set', to='web.variant')),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='variants',
            field=models.ManyToManyField(blank=True, through='web.VRel', to='web.variant'),
        ),
    ]
