# Generated by Django 5.0.1 on 2024-01-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='parent_variant',
        ),
    ]
