# Generated by Django 5.0.1 on 2024-01-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_variant_parent_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='main_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_line_variant', to='web.variant'),
        ),
    ]
