# Generated by Django 5.0.1 on 2024-01-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_variant_main_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='main_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_line_variant', to='web.variant'),
        ),
    ]
